//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsAlicia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int Sexo { get; set; }
        public string Password { get; set; }
        public Nullable<int> Nip { get; set; }
        public string FotoURL { get; set; }
        public Nullable<System.DateTime> FechaUsuario { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    }
}
